### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by kenchasonakai** [kitagawachihiro/spoTodo#47]
MVPリリースお疲れ様でした、下記の視点をもとにレビューいたします。

1. READMEから課題解決する実装がされているか&動いている
2. 静的コードチェックが入っている
3. 就活において十分な技術力を示せる機能を実装しているか
4. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか

## 静的コードチェックが入っている
余計な改行が入ったりしている箇所が見受けられましたのでrubocopを導入してLintチェックを通しましょう

## 就活において十分な技術力を示せる機能を実装しているか
- LINEログイン
- LINE MessagingAPI
- GoogleMapAPI

などの機能が実装出来ているのは良いと思います。

しかし少し機能数が物足りない印象がありますので追加することをお勧めします。
以下使ってみて追加すると良さそうかなと思った機能になりますのでアプリの方向性と合致していたら本リリースまでに追加する項目として参考にしてみてください
- 終わったTodoに公開・非公開を選んで写真付きで感想を投稿出来るようにする
- 他の人の公開Todoを閲覧できるようにする
- 他の人の公開Todoを検索出来るようにする
- 他の人の公開TodoをコピーしてTodoを登録出来るようにする
- Todo新規作成ページ閲覧時に範囲内の他の人のTodoがあればサジェストされるようにする

などを追加すると投稿してくれたデータを使ってよりサービスの幅を広げることが出来そうです

## UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
- 今できるTodoは？のところで`今いる場所の近くで出来るTodoリストを作ります。`と書いてあったので現在地付近で出来るTodoを追加出来ると思ったがなにも表示されなく思っているのと違う感じがしたので何が出来るのかを明示したりすると良さそうに思いました。
- サイドバーの色味が薄くて非アクティブになっている印象を受けましたのでもうすこし目立つ色合いにしてあげるとわかりやすそうです。

## 対応した方が良いこと
本リリースまでにやることに書いてある内容に加えて対応した方が良さそうなことを書いておきます

### Railsのバージョン
Rails5系はセキュリティサポートの期限が切れてしまっているので、何か特別な事情を面接時に説明出来なそうであれば6.1.7.6以上にアップデートしましょう
https://endoflife.date/rails

### 本リリース時までにやることに書いていなかった細かな項目
- OGP設定
- favicon設定

### 本リリース時までにやることで共有していただいた内容
- Todo検索機能
- チュートリアル用Todoの自動生成
- チェックされたTodoを1週間通過後Todoリストから自動削除（cron）
- レスポンスデザインの実装
- 管理機能
- 利用規約・プライバシーポリシーの作成
- Metaタグ追加、SEO対策
- コードの整形、Fat Controller解消
- レイアウト修正、ページ読み込み時の不具合解消
- 独自ドメイン取得、デプロイ先をAWSへ変更　※できたら
- LINE連携（Todo登録、Todoチェック）※できたら
- 位置情報と近い場所に紐づくTodoがない場合、 おすすめのカフェ情報（ユーザーが登録時に指定した興味のある情報）を通知する機能　※できたら

レビュー自体はLGTMですので、上記のレビューをタスクに落とし込み、issueに書きましたら、こちらのissueはcloseしていただいて大丈夫です。
また書き出したissueをもとに本リリースまでのスケジュールを教えていただけますでしょうか？
よろしくお願いいたします。

**Comment by kitagawachihiro** [comment]
お忙しいところレビューありがとうございます。

追加した方が良さそうな機能については具体的なご提案までありがとうございました。
プライベートな事を管理するアプリをイメージしていたため、
他者との「共有」は全く考えていなかったのですが、「共有」が技術的にもプラスで必要なのだと解釈しております。
ユーザーにとってメリットになり、自分のアプリのイメージとも合うTodoの「共有」を自分でも考えてから機能実装に移りたいと思います。

◾️本リリースまでのスケジュールは下記になります。
9/16~9/30 文言修正、サイドバーの色味修正、favicon設定などやり方がわかる修正や追加
10/1~10/8 追加機能の検討・実装
10/9~10/21 コードの整形、管理機能の作成、利用者規約の作成など調べることが必要な修正や追加
10/21~10/28 予備

よろしくお願いします。

**Comment by kitagawachihiro** [comment]
レビューをいただいた内容を踏まえ、追加実装を行いました。
